[documentation] update config.river sample for k8s ebpf use case (#3128)
* [readme] fix documentation to prevent load errors

Error: /etc/agent/config.river:61:47: field "targets" does not exist

60 |     forward_to = [pyroscope.write.endpoint.receiver]
61 |     targets = discovery.relabel.specific_pods.targets
   |                                               ^^^^^^^
62 | }

* Fix another error in pyrsocope_write

URL needs to be part of a endpoint structure.

---------

Co-authored-by: Christian Simon <simon@swine.de>