examples/ebpf-otel: Fix collector tag (#4425)
Tag  otel/opentelemetry-collector-contrib:0.129.0 doesn't exist:

```bash
$ docker-compose up --build
Pulling otel-collector (otel/opentelemetry-collector-contrib:0.129.0)...
ERROR: manifest for otel/opentelemetry-collector-contrib:0.129.0 not found: manifest unknown: manifest unknown
```

Switch to the nearest tag that works.

Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>